In [1]:
import lorentz
import importlib
import pylhe
import numpy as np
import utils as u
import NumpyClasses as npc

In [2]:
importlib.reload(u)

<module 'utils' from '/Users/roberto/scriptbelt/utils.py'>

In [13]:
importlib.reload(lorentz)

<module 'lorentz' from '/Users/roberto/humanroot/utils/PyLHEanalysis/lorentz.py'>

In [4]:
_fv=lorentz.LorentzVector(px=3,py=2,pz=1,e=14)
_pl=lorentz.LorentzVector(px=0.1,py=0.2,pz=0.3,e=1.6)

np.dot(_fv.NewTriadFromLorentzVector(second3vector=_pl.three_components() )['prime2x'],np.array([1,0,0]) )

array([ 0.40824829, -0.81649658,  0.40824829])

In [5]:
newBasis=_fv.NewTriadFromLorentzVector(second3vector=_pl.three_components() )
newBasis['x2prime']

array([[ 0.40824829, -0.81649658,  0.40824829],
       [ 0.43643578, -0.21821789, -0.87287156],
       [ 0.80178373,  0.53452248,  0.26726124]])

In [6]:
newpl=_pl.Change3DBasis(newBasis['vectors'])
print(newpl.components()) # same as in Mathematica

(1.3877787807814457e-17, -0.26186146828319085, 0.26726124191242434, 1.6)


In [7]:
_fv.beta_scalar() # Same as in Mathematica

0.2672612419124244

In [8]:
_lGen4VPrimeBoosted=newpl.BoostBetaAlongZ( _fv.beta_scalar() )
print(_lGen4VPrimeBoosted.components()) # Same as in Mathematica

(1.3877787807814457e-17, -0.26186146828319085, 0.7211102550927979, 1.734523400986977)


In [9]:
_lGen4VPrimeBoostedUnprimed=_lGen4VPrimeBoosted.Change3DBasisRotation( newBasis['prime2x'] )
print(_lGen4VPrimeBoostedUnprimed.components()) # Same as in Mathematica

(0.46388875270994456, 0.44259250180662973, 0.4212962509033148, 1.734523400986977)


#### Test of the function to get the Lepton $\phi$ in the Frame aligned along its mother W boson

In [16]:
_fv=lorentz.LorentzVector(px=3,py=-2,pz=1,e=14)
_pl=lorentz.LorentzVector(px=0.1,py=0.2,pz=0.3,e=1.6)

In [17]:
_pl.phi_wrt_reference(_fv)

0.9283639280080875

#### Test of the function to get the Lepton 4V in the Frame of rest of its mother W boson

In [10]:
Mother=lorentz.LorentzVector(px=3,py=2,pz=1,e=14)
Daughter=lorentz.LorentzVector(px=0.1,py=0.2,pz=0.3,e=1.6)

Daughter.ToMothersFrameWithZalongMotherParticleMomentum(Mother,DEBUG=True)



[ 0.40824829 -0.81649658  0.40824829]
[[ 0.40824829 -0.81649658  0.40824829]
 [ 0.43643578 -0.21821789 -0.87287156]
 [ 0.80178373  0.53452248  0.26726124]]
(1.3877787807814457e-17, -0.26186146828319085, 0.26726124191242434, 1.6)
0.2672612419124244
(1.3877787807814457e-17, -0.26186146828319085, -0.16641005886756888, 1.5862735376547568)
(-0.2477105912847126, -0.03180706085647507, 0.18409646957176246, 1.5862735376547568)


In [11]:
Mother=lorentz.LorentzVector(px=3,py=2,pz=1,e=14)
Daughter=lorentz.LorentzVector(px=0.1,py=0.2,pz=0.3,e=1.6)

Daughter.ToMothersFrameWithZalongMotherParticleMomentum(Mother)#,DEBUG=True)



(-0.2477105912847126, -0.03180706085647507, 0.18409646957176246, 1.5862735376547568)
